
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 14 15:53:24 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 36;
  public static final int INCREMENT = 34;
  public static final int CHAR = 47;
  public static final int CONST = 32;
  public static final int LOWER = 13;
  public static final int NOTEQUAL = 10;
  public static final int LPAREN = 25;
  public static final int GREATER = 11;
  public static final int SEMI = 24;
  public static final int CONTINUE = 17;
  public static final int MINUS = 39;
  public static final int DECREMENT = 35;
  public static final int RPAREN = 26;
  public static final int AND = 7;
  public static final int NOT_SAME = 16;
  public static final int OR = 8;
  public static final int COMMA = 27;
  public static final int CLASS = 18;
  public static final int DIV = 41;
  public static final int PLUS = 38;
  public static final int ASSIGN = 9;
  public static final int IF = 20;
  public static final int BOOLEAN = 46;
  public static final int EOF = 0;
  public static final int RETURN = 29;
  public static final int RBRACKET = 37;
  public static final int EQUAL = 30;
  public static final int GREATER_EQUAL = 12;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int NUMBER = 45;
  public static final int MOD = 40;
  public static final int IDENT = 48;
  public static final int BREAK = 2;
  public static final int VOID = 31;
  public static final int SAME = 15;
  public static final int LBRACE = 22;
  public static final int ELSE = 19;
  public static final int POINT = 43;
  public static final int ENUM = 33;
  public static final int READ = 3;
  public static final int WHILE = 5;
  public static final int RBRACE = 23;
  public static final int LOWER_EQUAL = 14;
  public static final int EXTENDS = 6;
  public static final int PROG = 21;
  public static final int PRINT = 28;
  public static final int DO = 4;
}

