
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 28 21:50:49 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 38;
  public static final int INCREMENT = 36;
  public static final int CHAR = 49;
  public static final int CONST = 34;
  public static final int LOWER = 15;
  public static final int NOTEQUAL = 12;
  public static final int LPAREN = 27;
  public static final int GREATER = 13;
  public static final int SEMI = 26;
  public static final int CONTINUE = 19;
  public static final int MINUS = 41;
  public static final int DECREMENT = 37;
  public static final int RPAREN = 28;
  public static final int AND = 9;
  public static final int NOT_SAME = 18;
  public static final int OR = 10;
  public static final int COMMA = 29;
  public static final int CLASS = 20;
  public static final int DIV = 43;
  public static final int PLUS = 40;
  public static final int ASSIGN = 11;
  public static final int IF = 22;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int RBRACKET = 39;
  public static final int TERNARY_IF = 4;
  public static final int EQUAL = 32;
  public static final int GREATER_EQUAL = 14;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int MUL = 44;
  public static final int NUMBER = 47;
  public static final int MOD = 42;
  public static final int TERNARY_ELSE = 5;
  public static final int IDENT = 50;
  public static final int BREAK = 2;
  public static final int VOID = 33;
  public static final int SAME = 17;
  public static final int LBRACE = 24;
  public static final int ELSE = 21;
  public static final int POINT = 45;
  public static final int ENUM = 35;
  public static final int READ = 3;
  public static final int WHILE = 7;
  public static final int RBRACE = 25;
  public static final int LOWER_EQUAL = 16;
  public static final int EXTENDS = 8;
  public static final int PROG = 23;
  public static final int PRINT = 30;
  public static final int DO = 6;
}

